<?php/* Neuse Sport Shop Range www.neusesportshop.com/gunrange   Designed by CyberSharks   version 1.4.7   26 May 2015   copyright (c) 2015 CyberSharks.net (www.CyberSharks.net)   */   /* results to database */if($_POST) {	$conn = mssql_connect('sql-shark.cybershark.net', 'neuseGunRange', 'shark#2015!');		var_dump($conn);		if(!$conn) {				echo $strerr = "ERROR: Failed to connect to MSSQL Server ('sql-shark.cybershark.net') : ".mssql_get_last_message();			}		mssql_select_db('neusegunrangedb', $conn)

		//Variables for Primary Acct. Holder
		$mem_id = $_POST['mem_id'];		$f_name_pah = $_POST['f_name_pah'];		$mi_pah = $_POST['mi_pah'];
		$l_name_pah = $_POST['l_name_pah'];		$email_pah = $_POST['email_pah];		$add_pah = $_POST['add_pah'];		$city_pah = $_POST['city_pah'];		$state_pah = $_POST['state_pah'];		$zip_pah = $_POST['zip_pah'];		$cell_pah = $_POST['cell_pah'];		$alt_no_pah = $_POST['alt_no_pah'];		$dob_pah = $_POST['dob_pah'];		$sex_pah = $_POST['sex_pah']; //drop down 		$pswd_pah = $_POST['pswd_pah'];		$re_pswd_pah = $_POST['re_pswd_pah'];
		//Variables for Secondary Acct. Holder		$name_sah = $_POST['name_sah'];		$email_sah = $_POST['email_sah'];		$cell_sah = $_POST['cell_sah'];		$dob_sah = $_POST['dob_sah'];		$sex_sah = $_POST['sex_sah']; //drop down 

		//Variables for account user 1
		$sec_under1_name = $_POST['sec_under1_name'];		$sec_under1_email = $_POST['sec_under1_email'];		$sec_under1_cell = $_POST['sec_under1_cell'];		$sec_under1_dob = $_POST['sec_under1_dob'];		$sec_under1_sex = $_POST['sec_under1_sex'];

		//Variables for account user 2
		$sec_under2_name = $_POST['sec_under2_name'];		$sec_under2_email = $_POST['sec_under2_email'];		$sec_under2_cell = $_POST['sec_under2_cell'];		$sec_under2_dob = $_POST['sec_under2_dob'];
		$sec_under2_sex = $_POST['sec_under2_sex'];				$mem_id = mssql_escape($mem_id);		$f_name_pah = mssql_escape($f_name_pah);		$mi_pah = mssql_escape($mi_pah);		$l_name_pah = mssql_escape($l_name_pah);		$email_pah = mssql_escape($email_pah);		$add_pah = mssql_escape($add_pah);		$city_pah = mssql_escape($city_pah);		$state_pah = mssql_escape($state_pah);		$zip_pah = mssql_escape($zip_pah);		$cell_pah = mssql_escape($cell_pah);		$alt_no_pah = mssql_escape($alt_no_pah);		$dob_pah = mssql_escape($dob_pah);		$sex_pah = mssql_escape($sex_pah);		$pswd_pah = mssql_escape($pswd_pah);		$re_pswd_pah = mssql_escape($re_pswd_pah);				$name_sah = mssql_escape($name_sah);		$email_sah = mssql_escape($email_sah);		$cell_sah = mssql_escape($cell_sah);		$dob_sah = mssql_escape($dob_sah);		$sex_sah = mssql_escape($sex_sah);				$sec_under1_name = mssql_escape($sec_under1_name);		$sec_under1_email = mssql_escape($sec_under1_email);		$sec_under1_cell = mssql_escape($sec_under1_cell);		$sec_under1_dob = mssql_escape($sec_under1_dob);		$sec_under1_sex = mssql_escape($sec_under1_sex);				$sec_under2_name = mssql_escape($sec_under2_name);		$sec_under2_email = mssql_escape($sec_under2_email);		$sec_under2_cell = mssql_escape($sec_under2_cell);		$sec_under2_dob = mssql_escape($sec_under2_dob);		$sec_under2_sex = mssql_escape($sec_under2_sex);						$sql = "SET IDENTITY_INSERT primary_cust ON			INSERT INTO primary_cust 			([f_name_pah]			,[mi_pah]			,[l_name_pah]			,[sex_pah]			,[dob_pah]			,[add_pah]			,[city_pah]			,[state_pah]			,[zip_pah]			,[cell_pah]			,[alt_no_pah]			,[email_pah]			,[pswd_pah]			,[re_pswd_pah]			,[name_sah]			,[sec_under1_name]			,[sec_under2_name]			)						SELECT '$_POST[f_name_pah]'			,'$_POST[mi_pah]'			,'$_POST[l_name_pah]'			,'$_POST[sex_pah]'			,'$_POST[dob_pah]'			,'$_POST[add_pah]'			,'$_POST[city_pah]'			,'$_POST[state_pah]'			,'$_POST[zip_pah]'			,'$_POST[cell_pah]'			,'$_POST[alt_no_pah]'			,'$_POST[email_pah]'			,'$_POST[pswd_pah]'			,'$_POST[re_pswd_pah]'			,'$_POST[name_sah]'			,'$_POST[sec_under1_name]'			,'$_POST[sec_under2_name]'					;			GO						mssql_query($sql, $conn);					mssql_close($conn);		
}

?>